sudo: false

language: node_js

node_js:
  - "stable"


before_script:
  - cd v1

script:
  - npm install
  - npm test

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

after_success: npm run coverage

notifications:
  email: false